version: 0.0
os: linux
files:
  - source: /
    destination: /home/server/partyfish
permissions:
  - object: /home/server/partyfish
    owner: server
hooks:
  BeforeInstall:
    - location: deploy/clean_workspace.sh
      timeout: 300
      runas: server
  AfterInstall:
    - location: deploy/install_dependencies.sh
      timeout: 300
      runas: server
  ApplicationStart:
    - location: deploy/start_server.sh
      timeout: 300
      runas: server
  ApplicationStop:
    - location: deploy/stop_server.sh
      timeout: 300
      runas: server
