version: 0.0
os: linux
files:
  - source: /
    destination: /home/server/partyfish
    overwrite: true
hooks:
  AfterInstall:
    - location: deploy/install_dependencies.sh
      timeout: 300
      runas: server
  ApplicationStart:
    - location: deploy/start_server.sh
      timeout: 300
      runas: server
  ApplicationStop:
    - location: deploy/stop_server.sh
      timeout: 300
      runas: server
